#include "LexerFsm.h"

BOOLEAN Available_Lookup[CHAR_POSIBILITIES] = {
    ['0'] = VALID_INPUT,['1'] = VALID_INPUT,['2'] = VALID_INPUT,['3'] = VALID_INPUT,
    ['4'] = VALID_INPUT,['5'] = VALID_INPUT,['6'] = VALID_INPUT,['7'] = VALID_INPUT,
    ['8'] = VALID_INPUT,['9'] = VALID_INPUT,


    ['a'] = VALID_INPUT,['b'] = VALID_INPUT,['c'] = VALID_INPUT,['d'] = VALID_INPUT,
    ['e'] = VALID_INPUT,['f'] = VALID_INPUT,['g'] = VALID_INPUT,['h'] = VALID_INPUT,
    ['i'] = VALID_INPUT,['j'] = VALID_INPUT,['k'] = VALID_INPUT,['l'] = VALID_INPUT,
    ['m'] = VALID_INPUT,['n'] = VALID_INPUT,['o'] = VALID_INPUT,['p'] = VALID_INPUT,
    ['q'] = VALID_INPUT,['r'] = VALID_INPUT,['s'] = VALID_INPUT,['t'] = VALID_INPUT,
    ['u'] = VALID_INPUT,['v'] = VALID_INPUT,['w'] = VALID_INPUT,['x'] = VALID_INPUT,
    ['y'] = VALID_INPUT,['z'] = VALID_INPUT,

    ['A'] = VALID_INPUT,['B'] = VALID_INPUT,['C'] = VALID_INPUT,['D'] = VALID_INPUT,
    ['E'] = VALID_INPUT,['F'] = VALID_INPUT,['G'] = VALID_INPUT,['H'] = VALID_INPUT,
    ['I'] = VALID_INPUT,['J'] = VALID_INPUT,['K'] = VALID_INPUT,['L'] = VALID_INPUT,
    ['M'] = VALID_INPUT,['N'] = VALID_INPUT,['O'] = VALID_INPUT,['P'] = VALID_INPUT,
    ['Q'] = VALID_INPUT,['R'] = VALID_INPUT,['S'] = VALID_INPUT,['T'] = VALID_INPUT,
    ['U'] = VALID_INPUT,['V'] = VALID_INPUT,['W'] = VALID_INPUT,['X'] = VALID_INPUT,
    ['Y'] = VALID_INPUT,['Z'] = VALID_INPUT,

    ['_'] = VALID_INPUT,['+'] = VALID_INPUT,['-'] = VALID_INPUT,['*'] = VALID_INPUT,
    ['/'] = VALID_INPUT,['='] = VALID_INPUT,['>'] = VALID_INPUT,['<'] = VALID_INPUT,
    ['%'] = VALID_INPUT,['&'] = VALID_INPUT,['|'] = VALID_INPUT,
    ['!'] = VALID_INPUT,['('] = VALID_INPUT,[')'] = VALID_INPUT,['{'] = VALID_INPUT,
    ['}'] = VALID_INPUT,[','] = VALID_INPUT,['#'] = VALID_INPUT,['"'] = VALID_INPUT,

	['\n'] = VALID_INPUT,['\t'] = VALID_INPUT,['\r'] = VALID_INPUT,[' '] = VALID_INPUT,
	['\0'] = VALID_INPUT,
};


enum State Lexer_FSM[NUM_OF_STATES][CHAR_POSIBILITIES] = {
    [STATE0] = {
        ['0'] = NUMBER,['1'] = NUMBER,['2'] = NUMBER,['3'] = NUMBER,
        ['4'] = NUMBER,['5'] = NUMBER,['6'] = NUMBER,['7'] = NUMBER,
        ['8'] = NUMBER,['9'] = NUMBER,

        ['a'] = IDENTIFIER,['b'] = B,['c'] = C,['d'] = D,
        ['e'] = E,['f'] = F,['g'] = G,['h'] = IDENTIFIER,
        ['i'] = I,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = P,
        ['q'] = IDENTIFIER,['r'] = R,['s'] = IDENTIFIER,['t'] = T,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = W,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,

        ['+'] = PLUS,['-'] = MINUS,['*'] = MULTIPLY,['/'] = DIVIDE,
		['='] = ASSIGN,['>'] = GREATER,['<'] = LESS,
		['%'] = MODULO,['&'] = AND,['|'] = OR,
		['!'] = NOT,['('] = L_PAREN,[')'] = R_PAREN,['{'] = L_BRACES,
		['}'] = R_BRACES,[','] = COMMA,

        ['"'] = STRING_LITERAL, ['#'] = COMMENT,
},

	[NUMBER] = {
		['0'] = NUMBER,['1'] = NUMBER,['2'] = NUMBER,['3'] = NUMBER,
		['4'] = NUMBER,['5'] = NUMBER,['6'] = NUMBER,['7'] = NUMBER,
		['8'] = NUMBER,['9'] = NUMBER,
	},

    [IDENTIFIER] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [B] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = BO,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = R,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
	[BR] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = BRE,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
	},
    [BRE] = {
        ['a'] = BREA,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [BREA] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = BREAK,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [BREAK] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [BO] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = BOO,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
    ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [BOO] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = BOOL,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [BOOL] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [C] = {
        ['a'] = CA,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = CH,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [CH] = {
        ['a'] = CHA,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [CHA] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = CHAN,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [CHAN] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = CHANG,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [CHANG] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = CHANGE,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [CHANGE] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [CA] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = CAL,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [CAL] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = CALL,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [CALL] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [CALL] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [D] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = DO,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [DO] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [E] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = EL,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [EL] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = ELS,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [ELS] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = ELSE,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [ELSE] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [F] = {
        ['a'] = FA,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = FO,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = FU,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FA] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = FAL,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FAL] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = FALS,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FALS] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = FALSE,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FALSE] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FO] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = FOR,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FOR] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FU] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = FUN,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FUN] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = FUNC,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FUNC] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = FUNCT,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FUNCT] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = FUNCTI,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FUNCTI] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = FUNCTIO,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FUNCTIO] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = FUNCTION,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [FUNCTION] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [G] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = GE,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [GE] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = GET,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [GET] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = GETS,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [GETS] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [I] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IF,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IN,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [IF] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [IN] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = INT,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [INT] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [P] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = PR,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [PR] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = PRI,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [PRI] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = PRIN,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [PRIN] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = PRINT,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [PRINT] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [R] = {
        ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
        ['e'] = RE,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
        ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
        ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
        ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
        ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
        ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
        ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
        ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
        ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
        ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
        ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
        ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
        ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
        ['-'] = IDENTIFIER,
    },
    [RE] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = RET,
    ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [RET] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
    ['u'] = RETU,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [RETU] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = RETUR,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
    ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [RETUR] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = RETURN,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
    ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [RETURN] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = RETURNS,['t'] = IDENTIFIER,
    ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [RETURNS] = {
['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
['y'] = IDENTIFIER,['z'] = IDENTIFIER,
['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
['-'] = IDENTIFIER,
    },
    [T] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = TR,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
    ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [TR] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
    ['u'] = TRU,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [TRU] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = TRUE,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
    ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [TRUE] = {
    ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
    ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
    ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
    ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
    ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
    ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
    ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
    ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
    ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
    ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
    ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
    ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
    ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
    ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
    ['-'] = IDENTIFIER,
    },
    [W] = {
     ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
     ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = WH,
     ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
     ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
     ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
     ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
     ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
     ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
     ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
     ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
     ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
     ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
     ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
     ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
     ['-'] = IDENTIFIER,
    },
    [WH] = {
     ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
     ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
     ['i'] = WHI,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
     ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
     ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
     ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
     ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
     ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
     ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
     ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
     ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
     ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
     ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
     ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
     ['-'] = IDENTIFIER,
    },
    [WHI] = {
     ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
     ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
     ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = WHIL,
     ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
     ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
     ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
     ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
     ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
     ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
     ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
     ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
     ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
     ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
     ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
     ['-'] = IDENTIFIER,
    },
    [WHIL] = {
     ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
     ['e'] = WHILE,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
     ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
     ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
     ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
     ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
     ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
     ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
     ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
     ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
     ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
     ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
     ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
     ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
     ['-'] = IDENTIFIER,
    },
    [WHILE] = {
     ['a'] = IDENTIFIER,['b'] = IDENTIFIER,['c'] = IDENTIFIER,['d'] = IDENTIFIER,
     ['e'] = IDENTIFIER,['f'] = IDENTIFIER,['g'] = IDENTIFIER,['h'] = IDENTIFIER,
     ['i'] = IDENTIFIER,['j'] = IDENTIFIER,['k'] = IDENTIFIER,['l'] = IDENTIFIER,
     ['m'] = IDENTIFIER,['n'] = IDENTIFIER,['o'] = IDENTIFIER,['p'] = IDENTIFIER,
     ['q'] = IDENTIFIER,['r'] = IDENTIFIER,['s'] = IDENTIFIER,['t'] = IDENTIFIER,
     ['u'] = IDENTIFIER,['v'] = IDENTIFIER,['w'] = IDENTIFIER,['x'] = IDENTIFIER,
     ['y'] = IDENTIFIER,['z'] = IDENTIFIER,
     ['A'] = IDENTIFIER,['B'] = IDENTIFIER,['C'] = IDENTIFIER,['D'] = IDENTIFIER,
     ['E'] = IDENTIFIER,['F'] = IDENTIFIER,['G'] = IDENTIFIER,['H'] = IDENTIFIER,
     ['I'] = IDENTIFIER,['J'] = IDENTIFIER,['K'] = IDENTIFIER,['L'] = IDENTIFIER,
     ['M'] = IDENTIFIER,['N'] = IDENTIFIER,['O'] = IDENTIFIER,['P'] = IDENTIFIER,
     ['Q'] = IDENTIFIER,['R'] = IDENTIFIER,['S'] = IDENTIFIER,['T'] = IDENTIFIER,
     ['U'] = IDENTIFIER,['V'] = IDENTIFIER,['W'] = IDENTIFIER,['X'] = IDENTIFIER,
     ['Y'] = IDENTIFIER,['Z'] = IDENTIFIER,
     ['-'] = IDENTIFIER,
    },
    
	[NOT] = { ['='] = NOT_EQUAL },
	[ASSIGN] = { ['='] = EQUAL },
	[GREATER] = { ['='] = GREATER_EQUAL },
	[LESS] = { ['='] = LESS_EQUAL },
	[AND] = { ['&'] = ALSO },
	[OR] = { ['|'] = EITHER },
    [DIVIDE] = { ['/'] = COMMENT_SINGLE_LINE },

    [COMMENT] = {
        ['0'] = COMMENT,['1'] = COMMENT,['2'] = COMMENT,['3'] = COMMENT,
        ['4'] = COMMENT,['5'] = COMMENT,['6'] = COMMENT,['7'] = COMMENT,
        ['8'] = COMMENT,['9'] = COMMENT,

        ['a'] = COMMENT,['b'] = COMMENT,['c'] = COMMENT,['d'] = COMMENT,
        ['e'] = COMMENT,['f'] = COMMENT,['g'] = COMMENT,['h'] = COMMENT,
        ['i'] = COMMENT,['j'] = COMMENT,['k'] = COMMENT,['l'] = COMMENT,
        ['m'] = COMMENT,['n'] = COMMENT,['o'] = COMMENT,['p'] = COMMENT,
        ['q'] = COMMENT,['r'] = COMMENT,['s'] = COMMENT,['t'] = COMMENT,
        ['u'] = COMMENT,['v'] = COMMENT,['w'] = COMMENT,['x'] = COMMENT,
        ['y'] = COMMENT,['z'] = COMMENT,
        ['A'] = COMMENT,['B'] = COMMENT,['C'] = COMMENT,['D'] = COMMENT,
        ['E'] = COMMENT,['F'] = COMMENT,['G'] = COMMENT,['H'] = COMMENT,
        ['I'] = COMMENT,['J'] = COMMENT,['K'] = COMMENT,['L'] = COMMENT,
        ['M'] = COMMENT,['N'] = COMMENT,['O'] = COMMENT,['P'] = COMMENT,
        ['Q'] = COMMENT,['R'] = COMMENT,['S'] = COMMENT,['T'] = COMMENT,
        ['U'] = COMMENT,['V'] = COMMENT,['W'] = COMMENT,['X'] = COMMENT,
        ['Y'] = COMMENT,['Z'] = COMMENT,
        ['-'] = COMMENT,

        ['+'] = COMMENT,['-'] = COMMENT,['*'] = COMMENT,['/'] = COMMENT,
        ['='] = COMMENT,['>'] = COMMENT,['<'] = COMMENT,
        ['%'] = COMMENT,['&'] = COMMENT,['|'] = COMMENT,
        ['!'] = COMMENT,['('] = COMMENT,[')'] = COMMENT,['{'] = COMMENT,
        ['}'] = COMMENT,[','] = COMMENT,

        ['"'] = COMMENT,['#'] = COMMENT_END,[' '] = COMMENT,
        ['\n'] = COMMENT,['\t'] = COMMENT,['\r'] = COMMENT,
        ['\0'] = COMMENT,
    },
    [COMMENT_SINGLE_LINE] = {
    ['0'] = COMMENT_SINGLE_LINE,['1'] = COMMENT_SINGLE_LINE,['2'] = COMMENT_SINGLE_LINE,['3'] = COMMENT_SINGLE_LINE,
    ['4'] = COMMENT_SINGLE_LINE,['5'] = COMMENT_SINGLE_LINE,['6'] = COMMENT_SINGLE_LINE,['7'] = COMMENT_SINGLE_LINE,
    ['8'] = COMMENT_SINGLE_LINE,['9'] = COMMENT_SINGLE_LINE,

    ['a'] = COMMENT_SINGLE_LINE,['b'] = COMMENT_SINGLE_LINE,['c'] = COMMENT_SINGLE_LINE,['d'] = COMMENT_SINGLE_LINE,
    ['e'] = COMMENT_SINGLE_LINE,['f'] = COMMENT_SINGLE_LINE,['g'] = COMMENT_SINGLE_LINE,['h'] = COMMENT_SINGLE_LINE,
    ['i'] = COMMENT_SINGLE_LINE,['j'] = COMMENT_SINGLE_LINE,['k'] = COMMENT_SINGLE_LINE,['l'] = COMMENT_SINGLE_LINE,
    ['m'] = COMMENT_SINGLE_LINE,['n'] = COMMENT_SINGLE_LINE,['o'] = COMMENT_SINGLE_LINE,['p'] = COMMENT_SINGLE_LINE,
    ['q'] = COMMENT_SINGLE_LINE,['r'] = COMMENT_SINGLE_LINE,['s'] = COMMENT_SINGLE_LINE,['t'] = COMMENT_SINGLE_LINE,
    ['u'] = COMMENT_SINGLE_LINE,['v'] = COMMENT_SINGLE_LINE,['w'] = COMMENT_SINGLE_LINE,['x'] = COMMENT_SINGLE_LINE,
    ['y'] = COMMENT_SINGLE_LINE,['z'] = COMMENT_SINGLE_LINE,
    ['A'] = COMMENT_SINGLE_LINE,['B'] = COMMENT_SINGLE_LINE,['C'] = COMMENT_SINGLE_LINE,['D'] = COMMENT_SINGLE_LINE,
    ['E'] = COMMENT_SINGLE_LINE,['F'] = COMMENT_SINGLE_LINE,['G'] = COMMENT_SINGLE_LINE,['H'] = COMMENT_SINGLE_LINE,
    ['I'] = COMMENT_SINGLE_LINE,['J'] = COMMENT_SINGLE_LINE,['K'] = COMMENT_SINGLE_LINE,['L'] = COMMENT_SINGLE_LINE,
    ['M'] = COMMENT_SINGLE_LINE,['N'] = COMMENT_SINGLE_LINE,['O'] = COMMENT_SINGLE_LINE,['P'] = COMMENT_SINGLE_LINE,
    ['Q'] = COMMENT_SINGLE_LINE,['R'] = COMMENT_SINGLE_LINE,['S'] = COMMENT_SINGLE_LINE,['T'] = COMMENT_SINGLE_LINE,
    ['U'] = COMMENT_SINGLE_LINE,['V'] = COMMENT_SINGLE_LINE,['W'] = COMMENT_SINGLE_LINE,['X'] = COMMENT_SINGLE_LINE,
    ['Y'] = COMMENT_SINGLE_LINE,['Z'] = COMMENT_SINGLE_LINE,
    ['-'] = COMMENT_SINGLE_LINE,

    ['+'] = COMMENT_SINGLE_LINE,['-'] = COMMENT_SINGLE_LINE,['*'] = COMMENT_SINGLE_LINE,['/'] = COMMENT_SINGLE_LINE,
    ['='] = COMMENT_SINGLE_LINE,['>'] = COMMENT_SINGLE_LINE,['<'] = COMMENT_SINGLE_LINE,
    ['%'] = COMMENT_SINGLE_LINE,['&'] = COMMENT_SINGLE_LINE,['|'] = COMMENT_SINGLE_LINE,
    ['!'] = COMMENT_SINGLE_LINE,['('] = COMMENT_SINGLE_LINE,[')'] = COMMENT_SINGLE_LINE,['{'] = COMMENT_SINGLE_LINE,
    ['}'] = COMMENT_SINGLE_LINE,[','] = COMMENT_SINGLE_LINE,

    ['"'] = COMMENT_SINGLE_LINE,['#'] = COMMENT_SINGLE_LINE,[' '] = COMMENT_SINGLE_LINE,
    ['\n'] = STATE0,['\t'] = COMMENT_SINGLE_LINE,['\r'] = COMMENT_SINGLE_LINE,
    ['\0'] = COMMENT_SINGLE_LINE,
    },
    [STRING_LITERAL] = {
        ['0'] = STRING_LITERAL,['1'] = STRING_LITERAL,['2'] = STRING_LITERAL,['3'] = STRING_LITERAL,
        ['4'] = STRING_LITERAL,['5'] = STRING_LITERAL,['6'] = STRING_LITERAL,['7'] = STRING_LITERAL,
        ['8'] = STRING_LITERAL,['9'] = STRING_LITERAL,

        ['a'] = STRING_LITERAL,['b'] = STRING_LITERAL,['c'] = STRING_LITERAL,['d'] = STRING_LITERAL,
        ['e'] = STRING_LITERAL,['f'] = STRING_LITERAL,['g'] = STRING_LITERAL,['h'] = STRING_LITERAL,
        ['i'] = STRING_LITERAL,['j'] = STRING_LITERAL,['k'] = STRING_LITERAL,['l'] = STRING_LITERAL,
        ['m'] = STRING_LITERAL,['n'] = STRING_LITERAL,['o'] = STRING_LITERAL,['p'] = STRING_LITERAL,
        ['q'] = STRING_LITERAL,['r'] = STRING_LITERAL,['s'] = STRING_LITERAL,['t'] = STRING_LITERAL,
        ['u'] = STRING_LITERAL,['v'] = STRING_LITERAL,['w'] = STRING_LITERAL,['x'] = STRING_LITERAL,
        ['y'] = STRING_LITERAL,['z'] = STRING_LITERAL,
        ['A'] = STRING_LITERAL,['B'] = STRING_LITERAL,['C'] = STRING_LITERAL,['D'] = STRING_LITERAL,
        ['E'] = STRING_LITERAL,['F'] = STRING_LITERAL,['G'] = STRING_LITERAL,['H'] = STRING_LITERAL,
        ['I'] = STRING_LITERAL,['J'] = STRING_LITERAL,['K'] = STRING_LITERAL,['L'] = STRING_LITERAL,
        ['M'] = STRING_LITERAL,['N'] = STRING_LITERAL,['O'] = STRING_LITERAL,['P'] = STRING_LITERAL,
        ['Q'] = STRING_LITERAL,['R'] = STRING_LITERAL,['S'] = STRING_LITERAL,['T'] = STRING_LITERAL,
        ['U'] = STRING_LITERAL,['V'] = STRING_LITERAL,['W'] = STRING_LITERAL,['X'] = STRING_LITERAL,
        ['Y'] = STRING_LITERAL,['Z'] = STRING_LITERAL,
        ['-'] = STRING_LITERAL,

        ['+'] = STRING_LITERAL,['-'] = STRING_LITERAL,['*'] = STRING_LITERAL,['/'] = STRING_LITERAL,
        ['='] = STRING_LITERAL,['>'] = STRING_LITERAL,['<'] = STRING_LITERAL,
        ['%'] = STRING_LITERAL,['&'] = STRING_LITERAL,['|'] = STRING_LITERAL,
        ['!'] = STRING_LITERAL,['('] = STRING_LITERAL,[')'] = STRING_LITERAL,['{'] = STRING_LITERAL,
        ['}'] = STRING_LITERAL,[','] = STRING_LITERAL,

        ['#'] = STRING_LITERAL,['"'] = STRING_LITERAL_END,[' '] = STRING_LITERAL,
    },


};

