DATA SEGMENT
x DW 0
INVALID_NUMBER_INPUT DB 0DH, 0AH, 'Input was not a number! Start Over', 0DH, 0AH, '$'
NEW_LINE_CHARS DB 0DH, 0AH, '$'
NUMBER_OUT_PUT_BUFFER DB 8 DUP(?)
DATA ENDS
STACK_SEG SEGMENT STACK
DW 1000H DUP(?)
STACK_SEG ENDS
CODE SEGMENT
ASSUME CS : CODE, DS : DATA, SS : STACK_SEG
START:
MOV AX, DATA
MOV DS, AX
MOV BP, SP
SUB SP, 0
BLOCK0:
MOV AX, 4C00H
INT 21H
CODE ENDS
END START
